### ISSUE TITLE
Uniformize indentation

### ISSUE THREAD

**Issue by bcalou** [ETombuyses/agora#2]
Vu sur la branche dev.

Votre indentation varie d'un fichier à l'autre. 2 espaces, 4, ça va vous jouer des tours car ça fait du diff de commit pour rien.

Utilisez 2 espaces et un outil comme Prettier (excellent) pour faire respecter ces règles communes.

Si vous êtes sur VSCode, activez le setting "format on save". Vous n'aurez plus qu'à passer sur chaque fichier, sauvegarder et le formattage se fera.

Ensuite faîtes un commit de formattage pour tout ça ;)

**Comment by ETombuyses** [comment]
Problème réglé !

Nous avons d'abord installé prettier CLI afin de formatter tous nos fichiers d'un coup en exécutant la commande "npx prettier --write .".

Nous avons également configuré Prettier pour VSCode en activant l'option Format On Save.
