### ISSUE TITLE
Use ternaries

### ISSUE THREAD

**Issue by bcalou** [ETombuyses/agora#34]
Dans certains cas l'usage de ternaire est un peu plus efficace / classique.

```
translateFactor === mounthsNumber - 1
    ? (translateFactor = 0)
    : (translateFactor += 1)
```

devient

```
translateFactor += (translateFactor === mounthsNumber - 1) ? 0 : 1;

**Comment by bcalou** [comment]
D'ailleurs... mounths ? ;)

**Comment by ETombuyses** [comment]
Petite faute de frappe effectivement !

Du coup j'ai bien repris l'idée de la ternaire afin d'assigner une valeur, mais pour l'effet de retour au premier slide une fois arrivé à la fin du slider je l'ai un peu modifiée pour qu'elle soit égale à 0 dans ce cas 😄 

```
translateFactor = translateFactor === monthsTasks.length - 1 ? 0 : translateFactor + 1
```

**Comment by bcalou** [comment]
Bien vu, c'est moi qui ai suggéré n'importe quoi ! Ajouter zéro, je ne sais pas à quoi je pensais... Ta version est bien !
